service:
  name: ignite-serverless

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws

functions:
  createTodo:
    handler: src/functions/createTodo.handle
    events:
      - http:
          path: /todos/{user_id}
          method: POST
          cors: true
    iamRoleStatements: 
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:PutItem
  getTodo:
    handler: src/functions/getTodo.handle
    events:
      - http:
          path: /todos/{user_id}
          method: GET
          cors: true
    iamRoleStatements: 
      - Effect: Allow
        Action:
          - dynamodb:Query
    
resources:
  Resources:
    usersTodos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTodos
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH